services:
  # 1. MySQL Database
  mysql:
    image: mysql:8.0
    container_name: bks_mysql
    restart: always
    environment:
      MYSQL_DATABASE: bks_social_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. MongoDB
  mongodb:
    image: mongo:latest
    container_name: bks_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Redis
  redis:
    image: redis:alpine
    container_name: bks_redis
    restart: always
    ports:
      - "6379:6379"

  # 4. MinIO (Object Storage)
  minio:
    image: minio/minio:latest
    container_name: bks_minio
    restart: always
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console UI port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # 5. Spring Boot Backend
  backend:
    build: .
    container_name: bks_backend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
      - redis
      - minio
    environment:
      # Liên kết qua Service Name của Docker thay vì localhost
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bks_social_db
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/bks_social_db
      - SPRING_DATA_REDIS_HOST=redis
      - MINIO_ENDPOINT=http://minio:9000
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

volumes:
  mysql_data:
  mongo_data:
  minio_data: